//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRegister
    {
        public int EID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string SSC_Year { get; set; }
        public string SSC_Result { get; set; }
        public string SSc_Board { get; set; }
        public string HSC_Year { get; set; }
        public string HSC_Result { get; set; }
        public string HSC_Board { get; set; }
        public string Gradute_University { get; set; }
        public string Passing_Year { get; set; }
        public string Result { get; set; }
        public string Grade { get; set; }
        public string Salary_Scale { get; set; }
        public string Commision_Percentage { get; set; }
        public string Increment { get; set; }
        public string Birth_Date { get; set; }
        public string Gender { get; set; }
        public string Married_or_Unmarried { get; set; }
        public string Blood_Group { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
    }
}
